version: "3.5"

services:
  goreleaser:
    build:
      context: .
      dockerfile: Dockerfile.build
    environment:
      - BUILDKITE_AGENT_JOB_API_SOCKET
      - BUILDKITE_AGENT_JOB_API_TOKEN
      - GOCACHE=/gocache
      - GOMODCACHE=/gomodcache
    working_dir: /go/src/github.com/buildkite/buildkite-mcp-server
    volumes:
      - ..:/go/src/github.com/buildkite/buildkite-mcp-server:cached
      - ~/gocache:/gocache
      - ~/gomodcache:/gomodcache      
      - ${BUILDKITE_AGENT_JOB_API_SOCKET}:${BUILDKITE_AGENT_JOB_API_SOCKET}
      - /var/run/docker.sock:/var/run/docker.sock
